// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv4LTjB71eOe6Z6kGeDv4B16LMv-NIhbw',
    appId: '1:590502566232:web:89fa0eb8e80f39b9146d2d',
    messagingSenderId: '590502566232',
    projectId: 'chatbottemplate-efacc',
    authDomain: 'chatbottemplate-efacc.firebaseapp.com',
    storageBucket: 'chatbottemplate-efacc.appspot.com',
    measurementId: 'G-EMF1C84WTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAi6uTW7Z4_dxZybXVhEPvp06cLAAOW_Y',
    appId: '1:590502566232:android:af4c5af7515fc5f1146d2d',
    messagingSenderId: '590502566232',
    projectId: 'chatbottemplate-efacc',
    storageBucket: 'chatbottemplate-efacc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKD8QC4cF4Be_JaFi71cyxsRoQGrTbcEI',
    appId: '1:590502566232:ios:013f993ea5eb9fb1146d2d',
    messagingSenderId: '590502566232',
    projectId: 'chatbottemplate-efacc',
    storageBucket: 'chatbottemplate-efacc.appspot.com',
    iosClientId: '590502566232-gcl3ou5l8h060nqcnd0ai7166418ds7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbotTemplate',
  );
}
